# Workflow for Python metrics generation (scheduled)
name: Scheduled task (Python)

on: 
  schedule: 
    - cron: '00 5 * * THU'
  
permissions: read-all

jobs:
  render-metrics:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Render metrics and Commit Results
        run: |
          python scripts/metrics.py
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit output/* -m 'Update metrics (Python)' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

      - name: Trigger Publish Workflow
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'publish-trigger',
            });